spin_version = "1"
authors = ["Seb Gomez <sebastiangomezcorrea@gmail.com>"]
description = "WASM DotNet sample"
name = "wasm-dotnet"
trigger = { type = "http", base = "/" }
version = "0.1.1"

[[component]]
id = "wasm-dotnet"
source = "./bin/web.wasm"
[component.trigger]
route = "/hello"
executor = { type = "wagi" }