apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-wasm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi-wasm
  template:
    metadata:
      labels:
        app: webapi-wasm
    spec:
      imagePullSecrets:
        - name: pullsecret
        #- name: regcred
      containers:
        - name: webapi
          #image: ghrc.io/sebagomez/webapi-wasm
          image: sebsregistry.azurecr.io/wasm-dotnet:latest
      nodeSelector:
        kubernetes.io/arch: "wasm32-wasi"
      tolerations:
        - key: "kubernetes.io/arch"
          operator: "Equal"
          value: "wasm32-wasi"
          effect: "NoExecute"
        - key: "node.kubernetes.io/network-unavailable"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "kubernetes.io/arch"
          operator: "Equal"
          value: "wasm32-wasi"
          effect: "NoSchedule"
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-wasm
spec:
  #type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: webapi-wasm