apiVersion: batch/v1
kind: Job
metadata:
  name: hello-wasm
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      containers:
      - image: sebagomez/hello-wasm:wasi
        name: hello
        # args: 
        # - "40"
        imagePullPolicy: Always
      restartPolicy: Never
      runtimeClassName: wasmtime-spin-v1 # needed for Azure, wasmtime for local minikube
      nodeSelector:
        run: wasm