apiVersion: v1
kind: Pod
metadata:
  name: greet
  labels:
    app: greet
spec:
  nodeSelector:
    kubernetes.io/arch: "wasm32-wasi"
  containers:
    - image: webassemblyhub.io/sebagomez/webapi-hello:latest
      imagePullPolicy: Always
      name: greet
      ports:
        - containerPort: 80
  tolerations:
    - key: "node.kubernetes.io/network-unavailable"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoExecute"
    - key: "kubernetes.io/arch"
      operator: "Equal"
      value: "wasm32-wasi"
      effect: "NoSchedule"