name: Build

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build docker for x64
      run: |
        make build_x64

    - name: Build wasm
      run: | 
        make build_wasm
