name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build -o $(pwd)/bin -f wasm.Dockerfile .
        pwd
        ls $(pwd)/bin
        
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
