name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        export out=$(pwd)/bin
        echo $out
        docker build -o $out -f wasm.Dockerfile .
        ls $out
        
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
