name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: |
        export out=$(pwd)/app
        mkdir $out
        echo $out
        docker build -o $out -f wasm.Dockerfile .

    - name: Install wasm-to-oci
      run: | 
        curl https://github.com/engineerd/wasm-to-oci/releases/download/v0.1.2/linux-amd64-wasm-to-oci -o wasm-to-oci
        chmod +x ./wasm-to-oci
        
        
    - name: wasm-to-oci
      run: ./wasm-to-oci --help

      
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
